version: '3.7'
services:
  nodejs-api:
    build: ./backend
    ports:
      - "3001:3001"
    container_name: nodejs-api
    links:
      - mongo-db
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - mongodb_data_container:/data/db
  react-ui:
    build: ./frontend
    ports:
      - '3000:3000'
    container_name: react-ui
    depends_on:
      - nodejs-api


volumes:
  mongodb_data_container: